### ISSUE TITLE
MergedAdapter has macro-in-macro issue that is disallowed since Haxe 4

### ISSUE THREAD

**Issue by ngrebenshikov** [profelis/hml#8]
https://haxe.org/manual/macro-limitations-macro-in-macro.html#trivia-expression-macro-in-macro

**Comment by profelis** [comment]
Any possibilities to fix? I’m very busy this week, relocation issues

**Comment by ngrebenshikov** [comment]
I've just put this feature to runtime instead of macro - https://github.com/jiveui/hml/commit/8365d64bc6f9bb2ee0d1215a18f54a03e728dc99

**Comment by profelis** [comment]
@ngrebenshikov can you create PR?

**Comment by ngrebenshikov** [comment]
https://github.com/profelis/hml/pull/9

**Comment by profelis** [comment]
Merged. Thx
